config/routes.rb
Rails.application.routes.draw do
  root 'reports#index'
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users, only: %i(index show update) do
    resources :followings, only: :index, module: :users
    resources :followers, only: :index, module: :users
  end

  resources :follow_relationships, only: %i(create destroy)

  resources :reports do
    resources :comments, only: %i(create destroy), module: :reports
  end

  resources :books do
    resources :comments, only: %i(create destroy), module: :books
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise :omniauthable, omniauth_providers: %i[github]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.github_data"] && session["devise.github_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  has_one_attached :image

  has_many :following_relationships, foreign_key: "follower_id", class_name: "FollowRelationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "FollowRelationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end
end

app/controllers/users/followers_controller.rb
class Users::FollowersController < ApplicationController
  def index
    @followers = User.find(params[:user_id]).followers
    render 'users/followers'
  end
end

app/controllers/users/followings_controller.rb
class Users::FollowingsController < ApplicationController
  def index
    @followings = User.find(params[:user_id]).followings
    render 'users/followings'
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: 'Github') if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    if user.update(user_params)
      redirect_to root_url
    else
      redirect_to edit_user_registration_url
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :postcode, :address, :biography, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_name(name)
    name.presence || '名無しさん'
  end
end

app/views/users/shared/_error_messages.html.slim
- if resource.errors.any?
  #error_explanation
    h2
      = I18n.t("errors.messages.not_saved",
      -                  count: resource.errors.count,
      -                  resource: resource.class.model_name.human.downcase)
    ul
      - resource.errors.full_messages.each do |message|
        li
          = message

app/views/users/shared/_links.html.slim
- if controller_name != 'sessions'
  = link_to t(".sign_in"), new_session_path(resource_name)
  br
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to t(".sign_up"), new_registration_path(resource_name)
  br
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to t(".forgot_your_password"), new_password_path(resource_name)
  br
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to t('.didn_t_receive_confirmation_instructions'), new_confirmation_path(resource_name)
  br
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to t('.didn_t_receive_unlock_instructions'), new_unlock_path(resource_name)
  br
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to t('.sign_in_with_provider', provider: OmniAuth::Utils.camelize(provider)), omniauth_authorize_path(resource_name, provider)
    br