config/routes.rb
Rails.application.routes.draw do
  root 'reports#index'
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users, only: %i(index show update) do
    resources :followings, only: :index, module: :users
    resources :followers, only: :index, module: :users
  end

  resources :follow_relationships, only: %i(create destroy)

  resources :reports do
    resources :comments, only: %i(create destroy), module: :reports
  end

  resources :books do
    resources :comments, only: %i(create destroy), module: :books
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  devise :omniauthable, omniauth_providers: %i[github]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.github_data"] && session["devise.github_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  has_one_attached :image

  has_many :following_relationships, foreign_key: "follower_id", class_name: "FollowRelationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "FollowRelationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end
end

app/controllers/users/followers_controller.rb
class Users::FollowersController < ApplicationController
  def index
    @followers = User.find(params[:user_id]).followers
    render 'users/followers'
  end
end

app/controllers/users/followings_controller.rb
class Users::FollowingsController < ApplicationController
  def index
    @followings = User.find(params[:user_id]).followings
    render 'users/followings'
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def github
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: 'Github') if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def update
    user = User.find(params[:id])
    if user.update(user_params)
      redirect_to root_url
    else
      redirect_to edit_user_registration_url
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :postcode, :address, :biography, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_name(name)
    name.presence || '名無しさん'
  end
end

app/views/users/_follow.html.slim
= form_for(current_user.following_relationships.build(following_id: user.id)) do |f|
  = f.hidden_field :following_id
  = f.submit "Follow"

app/views/users/_follow_form.html.slim
- unless user == current_user
  - if current_user.following?(user)
    = render 'users/unfollow', user: user
  - else
    = render 'users/follow', user: user

app/views/users/_stats.html.slim
table
  tr
    td= link_to t('link.following'), user_followings_path(user)
    td id="followings-count"
      = user.followings.count
  tr
    td= link_to t('link.follower'), user_followers_path(user)
    td id="followers-count"
      = user.followers.count

app/views/users/_unfollow.html.slim
= form_with(model: current_user.following_relationships.find_by(following_id: user.id), html: { method: :delete}) do |f|
  = f.submit "Unfollow"

app/views/users/_user.html.slim
= image_tag user.image, size: '100x100' if user.image.attached?
p
  strong
    = User.human_attribute_name(:name)
    | :
  = link_to user_name(user.name), user
p
  strong
    = User.human_attribute_name(:postcode)
    | :
  = user.postcode
p
  strong
    = User.human_attribute_name(:address)
    | :
  = user.address
p
  strong
    = User.human_attribute_name(:biography)
    | :
  = user.biography

app/views/users/_users.html.slim
- users.each do |user|
  = render 'users/user', user: user
  = render 'users/follow_form', user: user
  hr

app/views/users/followers.html.slim
h1= t('h.follower')
= render 'users/users', users: @followers

app/views/users/followings.html.slim
h1= t('h.following')
= render 'users/users', users: @followings

app/views/users/index.html.slim
h1
  = User.model_name.human(count: 2)

hr
= render 'users', users: @users

app/views/users/show.html.slim
h1
  = t('h.profile')
= render 'user', user: @user
= render 'stats', user: @user