config/routes.rb
Rails.application.routes.draw do
  root 'reports#index'
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users, only: %i(index show update) do
    resources :followings, only: :index, module: :users
    resources :followers, only: :index, module: :users
  end

  resources :follow_relationships, only: %i(create destroy)

  resources :reports do
    resources :comments, only: %i(create destroy), module: :reports
  end

  resources :books do
    resources :comments, only: %i(create destroy), module: :books
  end
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :comments, as: :commentable
  mount_uploader :picture, PictureUploader
  validates :title, presence: true
end

app/controllers/books/comments_controller.rb
class Books::CommentsController < CommentsController
  before_action :set_commentable

  private

  def set_commentable
    @commentable = Book.find(params[:book_id])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.page(params[:page]).per(10)
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :memo, :author, :picture)
    end
end

app/views/books/_form.html.slim
= form_with(model: book, local: true) do |form|
  - if book.errors.any?
    #error_explanation
      h2
        = pluralize(book.errors.count, "error")
        |  prohibited this book from being saved:
      ul
        - book.errors.full_messages.each do |message|
          li
            = message
  .field
    = form.label :title
    = form.text_field :title
  .field
    = form.label :memo
    = form.text_area :memo
  .field
    = form.label :author
    = form.text_area :author, id: :book_author
  .field
    = form.label :picture
    = form.file_field :picture, id: :book_picture
  .actions
    = form.submit

app/views/books/edit.html.slim
h1
  = "#{t('h.Editing')} #{Book.model_name.human}"
= render 'form', book: @book
= link_to t('link.Show'), @book
|  | 
= link_to t('link.Back'), books_path

app/views/books/index.html.slim
h1
  = Book.model_name.human(count: 2)

= paginate @books
= page_entries_info @books

table
  thead
    tr
      th
        = Book.human_attribute_name(:title)
      th
        = Book.human_attribute_name(:memo)
      th
        = Book.human_attribute_name(:author)
      th
        = Book.human_attribute_name(:picture)
      th[colspan="3"]
  tbody
    - @books.each do |book|
      tr
        td
          = book.title
        td
          = book.memo
        td
          = book.author
        td
          = book.picture
        td
          = link_to t('link.Show'), book
        td
          = link_to t('link.Edit'), edit_book_path(book)
        td
          = link_to t('link.Destroy'), book, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to "#{t('link.New')} #{Book.model_name.human}", new_book_path

app/views/books/new.html.slim
h1
  = "#{t('h.New')} #{Book.model_name.human}"
= render 'form', book: @book
= link_to t('link.Back'), books_path

app/views/books/show.html.slim
p
  strong
    = Book.human_attribute_name(:title)
    | :
  = @book.title
p
  strong
    = Book.human_attribute_name(:memo)
    | :
  = @book.memo
p
  strong
    = Book.human_attribute_name(:author)
    | :
  = @book.author
p
  strong
    = Book.human_attribute_name(:picture)
    | :
  = image_tag(@book.picture_url) if @book.picture.present?
= link_to t('link.Edit'), edit_book_path(@book)
|  | 
= link_to t('link.Back'), books_path

hr
= render partial: 'comments/comments', locals: { commentable: @book }
= render partial: 'comments/form', locals: { commentable: @book }