config/routes.rb
Rails.application.routes.draw do
  root 'reports#index'
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }

  resources :users, only: %i(index show update) do
    resources :followings, only: :index, module: :users
    resources :followers, only: :index, module: :users
  end

  resources :follow_relationships, only: %i(create destroy)

  resources :reports do
    resources :comments, only: %i(create destroy), module: :reports
  end

  resources :books do
    resources :comments, only: %i(create destroy), module: :books
  end
end

app/models/report.rb
class Report < ApplicationRecord
  has_many :comments, as: :commentable
  validates :title, presence: true
end

app/controllers/reports/comments_controller.rb
class Reports::CommentsController < CommentsController
  before_action :set_commentable

  private

  def set_commentable
    @commentable = Report.find(params[:report_id])
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.page(params[:page]).per(10)
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:title, :body)
    end
end

app/views/reports/_form.html.slim
= form_with(model: report, local: true) do |form|
  - if report.errors.any?
    #error_explanation
      h2
        = pluralize(report.errors.count, "error")
        |  prohibited this report from being saved:
      ul
        - report.errors.full_messages.each do |message|
          li
            = message
  .field
    = form.label :title
    = form.text_field :title
  .field
    = form.label :body
    = form.text_area :body
  .actions
    = form.submit

app/views/reports/edit.html.slim
h1
  = "#{t('h.Editing')} #{Report.model_name.human}"
= render 'form', report: @report
= link_to t('link.Show'), @report
|  | 
= link_to t('link.Back'), reports_path

app/views/reports/index.html.slim
h1
  = Report.model_name.human(count: 2)

= paginate @reports
= page_entries_info @reports

table
  thead
    tr
      th
        = Report.human_attribute_name(:title)
      th
        = Report.human_attribute_name(:body)
      th[colspan="3"]
  tbody
    - @reports.each do |report|
      tr
        td
          = report.title
        td
          = report.body
        td
          = link_to t('link.Show'), report
        td
          = link_to t('link.Edit'), edit_report_path(report)
        td
          = link_to t('link.Destroy'), report, method: :delete, data: { confirm: 'Are you sure?' }
br
= link_to "#{t('link.New')} #{Report.model_name.human}", new_report_path

app/views/reports/new.html.slim
h1
  = "#{t('h.New')} #{Report.model_name.human}"
= render 'form', report: @report
= link_to t('link.Back'), reports_path

app/views/reports/show.html.slim
p
  strong
    = Report.human_attribute_name(:title)
    | :
  = @report.title
p
  strong
    = Report.human_attribute_name(:body)
    | :
  = @report.body
= link_to t('link.Edit'), edit_report_path(@report)
|  | 
= link_to t('link.Back'), reports_path

hr
= render partial: 'comments/comments', locals: { commentable: @report }
= render partial: 'comments/form', locals: { commentable: @report }